### Insert User

POST http://localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
  "namalengkap": "Joko Susanto",
  "username" : "jokoaja",
  "password" : "rahasia",
  "status" : "Active"
}


### Get User

GET http://localhost:8080/api/users/jokoaja
Accept: application/json
Content-Type: application/json


### Remove Data Users

DELETE http://localhost:8080/api/users/jokoaja
Accept: application/json
Content-Type: application/json

